drop table if exists alert_log cascade;
drop table if exists child_watch_policy cascade;
drop table if exists viewing_history cascade;
drop table if exists children cascade;
drop table if exists report_daily cascade;
drop table if exists report_week cascade;
drop table if exists report_month cascade;
drop table if exists analysis_history cascade;
drop table if exists app_runtime_settings cascade;
drop table if exists users cascade;

create table users (
  user_id int primary key,
  user_name varchar(100) not null,
  birth_year int not null
);

create table children (
  child_id int primary key,
  user_id int not null,
  child_name varchar(100) not null,
  birth_year int not null,
  constraint fk_children_user
    foreign key (user_id)
    references users (user_id)
    on delete cascade
);

create table viewing_history (
  viewing_id int primary key,
  user_id int not null,
  child_id int not null,
  video_id varchar(120) not null,
  watch_time timestamp not null,
  watch_duration int not null,
  constraint fk_viewing_history_user
    foreign key (user_id)
    references users (user_id)
    on delete cascade,
  constraint fk_viewing_history_child
    foreign key (child_id)
    references children (child_id)
    on delete cascade
);

create table child_watch_policy (
  child_id int primary key,
  daily_limit_minutes int not null default 120,
  weekday_start_hour int not null default 7,
  weekday_end_hour int not null default 21,
  weekend_start_hour int not null default 8,
  weekend_end_hour int not null default 22,
  notification_threshold int not null default 70,
  auto_block_enabled boolean not null default true,
  updated_at timestamp not null default current_timestamp,
  constraint fk_child_watch_policy_child
    foreign key (child_id)
    references children (child_id)
    on delete cascade
);

create table alert_log (
  alert_id int primary key,
  viewing_id int not null,
  alert_type varchar(80) not null,
  risk_level varchar(40) not null,
  message_text varchar(500) not null,
  constraint fk_alert_log_viewing
    foreign key (viewing_id)
    references viewing_history (viewing_id)
    on delete cascade
);

create table report_daily (
  report_id int primary key,
  family_id int not null,
  compare_time int not null,
  count_alert_type int not null,
  constraint fk_report_daily_family
    foreign key (family_id)
    references users (user_id)
    on delete cascade
);

create table report_week (
  report_id int primary key,
  family_id int not null,
  compare_time int not null,
  count_alert_type int not null,
  constraint fk_report_week_family
    foreign key (family_id)
    references users (user_id)
    on delete cascade
);

create table report_month (
  report_id int primary key,
  family_id int not null,
  compare_time int not null,
  count_alert_type int not null,
  constraint fk_report_month_family
    foreign key (family_id)
    references users (user_id)
    on delete cascade
);

create table analysis_history (
  analysis_id bigint generated by default as identity primary key,
  input_url varchar(1000) not null,
  video_id varchar(120),
  title varchar(300),
  category_name_ko varchar(120),
  duration_seconds int,
  is_short_form boolean not null default false,
  blocked_by_category boolean not null default false,
  has_violence boolean not null default false,
  violence_score double precision,
  violence_positive_windows int,
  has_nudity boolean not null default false,
  nudity_match_count int,
  harmful boolean not null default false,
  harmful_reasons_json text,
  status varchar(40) not null,
  error_message text,
  created_at timestamp not null default current_timestamp
);

create table app_runtime_settings (
  settings_id smallint primary key,
  privacy_consent boolean not null default false,
  addiction_monitor_enabled boolean not null default false,
  updated_at timestamp not null default current_timestamp,
  constraint chk_app_runtime_settings_singleton
    check (settings_id = 1)
);

create index idx_children_user_id
  on children (user_id);

create index idx_viewing_history_user_time
  on viewing_history (user_id, watch_time desc);

create index idx_viewing_history_child_time
  on viewing_history (child_id, watch_time desc);

create index idx_alert_log_viewing_id
  on alert_log (viewing_id);

create index idx_child_watch_policy_child_id
  on child_watch_policy (child_id);

create index idx_report_daily_family_id
  on report_daily (family_id);

create index idx_report_week_family_id
  on report_week (family_id);

create index idx_report_month_family_id
  on report_month (family_id);

create index idx_analysis_history_created_at
  on analysis_history (created_at desc);
